# Site settings
title: Régius Kachimareck 
description: A page about my software development skills and personal projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Régius A. Kachimareck
user_description: Régius Andrei Kachimareck. Software developer. Computer science student in PUCPR. Curitiba, PR, Brazil.
user_title: Software Developer
email: regiusandrei@gmail.com
github_username:  RegiusK

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
